--
-- PostgreSQL database dump
--

\restrict 981Th8Y3LN3QTzfBJ39BjOs3lG0h4ErbJEQgZwHk9mPLT9ak4DnRRUUpgui95NM

-- Dumped from database version 17.7
-- Dumped by pg_dump version 17.7

-- Started on 2026-01-02 12:05:03

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2 (class 3079 OID 16487)
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- TOC entry 4966 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16652)
-- Name: app_counters; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_counters (
    id integer NOT NULL,
    global_counter bigint NOT NULL,
    personal_counter bigint NOT NULL
);


ALTER TABLE public.app_counters OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16655)
-- Name: billing_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.billing_requests (
    request_token uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_input_ticket character varying(80) NOT NULL,
    total_amount numeric NOT NULL,
    client_email character varying(100) NOT NULL,
    rfc character varying(13) NOT NULL,
    status_id smallint NOT NULL,
    error character varying(150),
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    br_retry_count integer,
    ticket_id bigint
);


ALTER TABLE public.billing_requests OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16661)
-- Name: billing_statuses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.billing_statuses (
    id bigint NOT NULL,
    code character varying(20) NOT NULL,
    description text
);


ALTER TABLE public.billing_statuses OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16666)
-- Name: billing_statuses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.billing_statuses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.billing_statuses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16667)
-- Name: clientes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.clientes (
    cliente_id integer NOT NULL,
    nombre character varying(255),
    email character varying(255),
    rfc character varying(20),
    regimen_fiscal character varying(50),
    descripcion_regimen character varying(150),
    street character varying(255),
    house_number character varying(50),
    city character varying(100),
    postal_code character varying(10),
    external_id character varying(50)
);


ALTER TABLE public.clientes OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16672)
-- Name: clientes_cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.clientes ALTER COLUMN cliente_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16673)
-- Name: invoices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoices (
    ins_id bigint NOT NULL,
    cadena_cfdi text,
    certificado_sat text,
    sello_cfdi text,
    sello_sat text,
    folio_factura text,
    folio_fiscal text,
    payment_method character varying(50),
    pdf_file character varying(255),
    pdf_xml character varying(255),
    version_timbre character varying(255),
    total numeric(15,6),
    date_create timestamp(6) without time zone,
    fecha_cfdi timestamp(6) without time zone,
    fecha_cancelacion timestamp(6) without time zone
);


ALTER TABLE public.invoices OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16678)
-- Name: invoices_ins_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invoices ALTER COLUMN ins_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoices_ins_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16679)
-- Name: ticket_lines; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ticket_lines (
    tkl_id bigint NOT NULL,
    tk_id bigint NOT NULL,
    tckl_id uuid,
    descripcion character varying(255),
    clave_prod_serv character varying(255),
    clave_unidad character varying(255),
    no_identificacion character varying(255),
    porcentaje_descuento character varying(255),
    tax_rate_type_code character varying(255),
    cantidad numeric(15,6),
    valor_unitario numeric(15,6),
    base numeric(15,6),
    descuento numeric(15,6),
    taxrate numeric(15,6),
    amount numeric(15,6),
    date_create timestamp(6) without time zone
);


ALTER TABLE public.ticket_lines OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16684)
-- Name: ticket_lines_tkl_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ticket_lines ALTER COLUMN tkl_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_lines_tkl_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16685)
-- Name: tickets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tickets (
    tk_id bigint NOT NULL,
    id_ticket character varying(255),
    status character varying(255),
    cancellation_status character varying(255),
    comentarios_sap character varying(255),
    error_sap character varying(255),
    error_timbrado character varying(255),
    forma_pago character varying(255),
    system_id character varying(255),
    system_group_id character varying(255),
    total_amount numeric(15,6),
    is_global boolean,
    is_sap boolean,
    objectkey uuid,
    create_date timestamp(6) without time zone,
    date_created_ticket timestamp(6) without time zone,
    cliente_id integer,
    ins_id bigint
);


ALTER TABLE public.tickets OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16690)
-- Name: tickets_tk_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tickets ALTER COLUMN tk_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tickets_tk_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4949 (class 0 OID 16652)
-- Dependencies: 218
-- Data for Name: app_counters; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.app_counters (id, global_counter, personal_counter) FROM stdin;
\.


--
-- TOC entry 4950 (class 0 OID 16655)
-- Dependencies: 219
-- Data for Name: billing_requests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.billing_requests (request_token, user_input_ticket, total_amount, client_email, rfc, status_id, error, created_at, updated_at, br_retry_count, ticket_id) FROM stdin;
550e8400-e29b-41d4-a716-446655440000	TICKET-01	100.00	test@cliente.com	XAXX010101000	1	\N	\N	\N	\N	\N
887d1e1a-3f30-4322-91b2-fe4ec2422979	REQUEST-0125	111	test10@mail.com	ABC9512317C0	1	\N	2025-12-31 11:16:05.126983-07	2025-12-31 11:16:05.126983-07	\N	\N
0461a4c4-1bfe-4df9-bea3-a9c06df088fb	REQUEST-8	100	test@mail.com	XAXX010101000	1	\N	2025-12-31 11:17:42.296469-07	2025-12-31 11:17:42.296469-07	\N	\N
f1c7b525-cdca-4793-a523-ca58d6d63670	REQUEST-015	111	test10@mail.com	ABC9512317C0	4	\N	2025-12-31 11:27:58.796236-07	2025-12-31 11:28:03.99016-07	\N	\N
504f5e49-4ec0-430a-9db5-65aa3e9973c8	REQUEST-999	1200	test@mail.com	XAXX010101000	4	\N	2025-12-31 11:29:20.503018-07	2025-12-31 11:29:25.523668-07	\N	\N
\.


--
-- TOC entry 4951 (class 0 OID 16661)
-- Dependencies: 220
-- Data for Name: billing_statuses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.billing_statuses (id, code, description) FROM stdin;
1	PENDING	Petición recibida y encolada
2	VALIDATING	Validando ticket
3	STAMPING	Enviando al PAC
4	SUCCESS	Factura generada
5	MAIL_FAILED	Error enviando correo
6	ERROR	Proceso fallido
\.


--
-- TOC entry 4953 (class 0 OID 16667)
-- Dependencies: 222
-- Data for Name: clientes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.clientes (cliente_id, nombre, email, rfc, regimen_fiscal, descripcion_regimen, street, house_number, city, postal_code, external_id) FROM stdin;
\.


--
-- TOC entry 4955 (class 0 OID 16673)
-- Dependencies: 224
-- Data for Name: invoices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invoices (ins_id, cadena_cfdi, certificado_sat, sello_cfdi, sello_sat, folio_factura, folio_fiscal, payment_method, pdf_file, pdf_xml, version_timbre, total, date_create, fecha_cfdi, fecha_cancelacion) FROM stdin;
\.


--
-- TOC entry 4957 (class 0 OID 16679)
-- Dependencies: 226
-- Data for Name: ticket_lines; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ticket_lines (tkl_id, tk_id, tckl_id, descripcion, clave_prod_serv, clave_unidad, no_identificacion, porcentaje_descuento, tax_rate_type_code, cantidad, valor_unitario, base, descuento, taxrate, amount, date_create) FROM stdin;
\.


--
-- TOC entry 4959 (class 0 OID 16685)
-- Dependencies: 228
-- Data for Name: tickets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tickets (tk_id, id_ticket, status, cancellation_status, comentarios_sap, error_sap, error_timbrado, forma_pago, system_id, system_group_id, total_amount, is_global, is_sap, objectkey, create_date, date_created_ticket, cliente_id, ins_id) FROM stdin;
\.


--
-- TOC entry 4967 (class 0 OID 0)
-- Dependencies: 221
-- Name: billing_statuses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.billing_statuses_id_seq', 1, false);


--
-- TOC entry 4968 (class 0 OID 0)
-- Dependencies: 223
-- Name: clientes_cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.clientes_cliente_id_seq', 1, false);


--
-- TOC entry 4969 (class 0 OID 0)
-- Dependencies: 225
-- Name: invoices_ins_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.invoices_ins_id_seq', 1, false);


--
-- TOC entry 4970 (class 0 OID 0)
-- Dependencies: 227
-- Name: ticket_lines_tkl_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ticket_lines_tkl_id_seq', 1, false);


--
-- TOC entry 4971 (class 0 OID 0)
-- Dependencies: 229
-- Name: tickets_tk_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tickets_tk_id_seq', 1, false);


--
-- TOC entry 4783 (class 2606 OID 16692)
-- Name: app_counters app_counters_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_counters
    ADD CONSTRAINT app_counters_pkey PRIMARY KEY (id);


--
-- TOC entry 4785 (class 2606 OID 16694)
-- Name: billing_requests billing_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.billing_requests
    ADD CONSTRAINT billing_requests_pkey PRIMARY KEY (request_token);


--
-- TOC entry 4789 (class 2606 OID 16696)
-- Name: billing_statuses billing_statuses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.billing_statuses
    ADD CONSTRAINT billing_statuses_pkey PRIMARY KEY (id);


--
-- TOC entry 4792 (class 2606 OID 16698)
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_pkey PRIMARY KEY (cliente_id);


--
-- TOC entry 4794 (class 2606 OID 16700)
-- Name: invoices invoices_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_pkey PRIMARY KEY (ins_id);


--
-- TOC entry 4796 (class 2606 OID 16702)
-- Name: ticket_lines ticket_lines_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_lines
    ADD CONSTRAINT ticket_lines_pkey PRIMARY KEY (tkl_id);


--
-- TOC entry 4798 (class 2606 OID 16704)
-- Name: tickets tickets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_pkey PRIMARY KEY (tk_id);


--
-- TOC entry 4786 (class 1259 OID 16728)
-- Name: idx_billing_requests_user_input_ticket; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_billing_requests_user_input_ticket ON public.billing_requests USING btree (user_input_ticket);


--
-- TOC entry 4787 (class 1259 OID 16746)
-- Name: idx_unique_billing_request; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_unique_billing_request ON public.billing_requests USING btree (user_input_ticket, rfc) WHERE (status_id <> 6);


--
-- TOC entry 4790 (class 1259 OID 16706)
-- Name: uni_billing_statuses_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uni_billing_statuses_code ON public.billing_statuses USING btree (code);


--
-- TOC entry 4799 (class 2606 OID 16729)
-- Name: billing_requests fk_billing_requests_status; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.billing_requests
    ADD CONSTRAINT fk_billing_requests_status FOREIGN KEY (status_id) REFERENCES public.billing_statuses(id);


--
-- TOC entry 4800 (class 2606 OID 16741)
-- Name: billing_requests fk_billing_requests_tickets; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.billing_requests
    ADD CONSTRAINT fk_billing_requests_tickets FOREIGN KEY (ticket_id) REFERENCES public.tickets(tk_id);


--
-- TOC entry 4802 (class 2606 OID 16712)
-- Name: tickets fk_ticket_cliente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT fk_ticket_cliente FOREIGN KEY (cliente_id) REFERENCES public.clientes(cliente_id);


--
-- TOC entry 4803 (class 2606 OID 16717)
-- Name: tickets fk_ticket_invoice; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT fk_ticket_invoice FOREIGN KEY (ins_id) REFERENCES public.invoices(ins_id);


--
-- TOC entry 4801 (class 2606 OID 16722)
-- Name: ticket_lines fk_ticket_lines_ticket; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_lines
    ADD CONSTRAINT fk_ticket_lines_ticket FOREIGN KEY (tk_id) REFERENCES public.tickets(tk_id);


-- Completed on 2026-01-02 12:05:03

--
-- PostgreSQL database dump complete
--

\unrestrict 981Th8Y3LN3QTzfBJ39BjOs3lG0h4ErbJEQgZwHk9mPLT9ak4DnRRUUpgui95NM

